elasticsearch_url: "http://babayaga11.local:9220"
elasticsearch_index: "nuix1"
username: "noauth"
password: "noauth"
metadata_profile_name: "Siren_Nuix_Export_Metadata_Profile"
temp_directory: "C:/Users/du/AppData/Roaming/Nuix"
catch_count: 100
